### ISSUE TITLE
Develop from scratch

### ISSUE THREAD

**Issue by Dulyaaa** [asthasharma98/Heart-Disease-Prediction-Deployment#1]
Hi @asthasharma98, I'm newbie to the ML/AI world. While I'm browsing I saw this project and now I want to try out this project by myself. I cloned your project and It's worked without any errors though I followed the steps that you are mentioned in `Readme.md` file. 

Now I want to build this project from scratch; beginning to the end. So could you please tell me what's first and then what. (Like how to initialize the project) And also I have a big question where from that `heart-disease-prediction-knn-model.pkl` file came? Is that a `.ipynb` file?

 Anyhow it will be grateful if you can provide more information. I would like to appreciate your response and thanks in advance😊.

**Comment by asthasharma98** [comment]
Hello @Dulyaaa , 
Here is the link of my article [How to develop an end to end  ML project](https://astha-s15.medium.com/how-to-develop-an-end-to-end-machine-learning-project-3b3488663e01). In this article I have tried my best to explain all the steps that is require to develop an complete end to end project from the scratch in detail.

Now about your Question on .pkl file so let me try to explain this in the simplest possible terms -
"The pickling process in Python does just what vinegar-based syrup does to chillies and other foods, it preserves something for later use. Python-pickling does the same thing for Python objects. It creates a serialized, byte-wise .pkl file so that the objects can be saved in a file and loaded and used in a program later on.
To know more about this, you can refer [this](https://www.datacamp.com/community/tutorials/pickle-python-tutorial) link.

As you are completely new in DS/ML world so I want to share few things that I wish I would have followed earlier... 

Don't get so overwhelmed and fascinated by the trendy libraries and ML models. Try to spend as much time as possible in understanding the problem statement like what is the nature of the problem you are trying to solve and then collect, process and transform data according to the requirements or most of the time you already have the dataset and from the given data figure out what can be done with the data and how it can be useful , find hidden trends and then decide what kind of problems can be solved with the data. Don't directly jump to modelling part focus more on EDA.  
Try to get your hands strong on the fundamentals of Python and statistics as learning tools are equally important.
Try to be a part of some data science/ML community and contribute in some open source projects so that you can get an idea of how an industry level projects work because only doing Kaggle projects simply won't help much.
There are still lot many things that you will eventually learn as you move further in this field. So keep exploring.

If you want you can also refer [this](https://jovian.ai/learn/data-analysis-with-python-zero-to-pandas) course for python basics and EDA 

I hope this will help you😊!!

**Comment by Dulyaaa** [comment]
ohhh..!! Yeah, I got it. That article is very helpful. And thanks for all the information that you've provided.😇
